version: '3.7'
services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - ./artifacts/init_db:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=base
      - MYSQL_USER=adm
      - MYSQL_PASSWORD=9mRE
